### ISSUE TITLE
@rpc() doesn't work with MessagePackDocument, MessagePackRpc and JsonDocument

### ISSUE THREAD

**Issue by Pastafarianist** [arskom/spyne#457] opened 2015-08-27 10:50 UTC
Server code (`spyne_test_server.py`):

```python
import logging
logging.basicConfig(level=logging.DEBUG)

from spyne.application import Application
from spyne.decorator import rpc
from spyne.service import ServiceBase
from spyne.server.zeromq import ZeroMQServer

from spyne.protocol.msgpack import MessagePackDocument
from spyne.protocol.msgpack import MessagePackRpc
from spyne.protocol.json import JsonDocument
from spyne.protocol.xml import XmlDocument

class HelloWorldService(ServiceBase):
    @rpc()
    def say_hello(ctx):
        print('hello')

application = Application([HelloWorldService],
    tns='spyne.examples.hello',
    # in_protocol=MessagePackDocument(validator='soft'),
    # out_protocol=MessagePackDocument()
    # in_protocol=MessagePackRpc(validator='soft'),
    # out_protocol=MessagePackRpc()
    # in_protocol=JsonDocument(validator='soft'),
    # out_protocol=JsonDocument()
    in_protocol=XmlDocument(validator='soft'),
    out_protocol=XmlDocument()
)
if __name__ == '__main__':
    server = ZeroMQServer(application,
                           'tcp://0.0.0.0:5555')
    server.serve_forever()
```

Client code (`spyne_test_client.py`):

```python
from spyne.client.zeromq import ZeroMQClient
from spyne_test_server import application

client = ZeroMQClient('tcp://0.0.0.0:5555', application)

client.service.say_hello()
```

`MessagePackDocument` crashes in client code:

    DEBUG:spyne.interface._base:populating 'spyne_test_server.HelloWorldService ({spyne_test_server}HelloWorldService)' types...
    DEBUG:spyne.interface._base:    adding class "<class 'spyne.model.complex.say_hello'>" for '{spyne.examples.hello}say_hello'
    DEBUG:spyne.interface._base:    adding class "<class 'spyne.model.complex.say_helloResponse'>" for '{spyne.examples.hello}say_helloResponse'
    DEBUG:spyne.interface._base:populating 'spyne_test_server.HelloWorldService' methods...
    DEBUG:spyne.interface._base:    adding method 'say_hello' to match '{spyne.examples.hello}say_hello' tag.
    DEBUG:spyne.interface._base:From this point on, you're not supposed to make any changes to the class & method structure of the exposed services.
    DEBUG:spyne.util.appreg:Registering <spyne.application.Application object at 0x7fa7387a4810> as ('spyne.examples.hello', 'Application')
    DEBUG:spyne.protocol.dictdoc:   header : None
    DEBUG:spyne.protocol.dictdoc:   body   : {'faultcode': 'Client', 'faultstring': 'Empty request', 'detail': None}
    Traceback (most recent call last):
      File "spyne_test_client.py", line 6, in <module>
        client.service.say_hello()
      File "/usr/lib64/python2.7/site-packages/spyne/client/zeromq.py", line 43, in __call__
        self.get_in_object(self.ctx)
      File "/usr/lib64/python2.7/site-packages/spyne/client/_base.py", line 144, in get_in_object
        message=self.app.in_protocol.RESPONSE)
      File "/usr/lib64/python2.7/site-packages/spyne/protocol/dictdoc.py", line 218, in decompose_incoming_envelope
        raise ValidationError("Need a dictionary with exacltly one key "
    spyne.error.ValidationError: Fault(Client.ValidationError: 'The value "\'Need a dictionary with exacltly one key as method name.\'" could not be validated.')

`MessagePackRpc` crashes in server code:

    DEBUG:spyne.interface._base:populating '__main__.HelloWorldService ({HelloWorldService.HelloWorldService}HelloWorldService)' types...
    DEBUG:spyne.interface._base:    adding class "<class 'spyne.model.complex.say_hello'>" for '{spyne.examples.hello}say_hello'
    DEBUG:spyne.interface._base:    adding class "<class 'spyne.model.complex.say_helloResponse'>" for '{spyne.examples.hello}say_helloResponse'
    DEBUG:spyne.interface._base:populating '__main__.HelloWorldService' methods...
    DEBUG:spyne.interface._base:    adding method 'say_hello' to match '{spyne.examples.hello}say_hello' tag.
    DEBUG:spyne.interface._base:From this point on, you're not supposed to make any changes to the class & method structure of the exposed services.
    DEBUG:spyne.util.appreg:Registering <spyne.application.Application object at 0x7fd73e1e9350> as ('spyne.examples.hello', 'Application')
    Traceback (most recent call last):
      File "spyne_test_server.py", line 33, in <module>
        server.serve_forever()
      File "/usr/lib64/python2.7/site-packages/spyne/server/zeromq.py", line 63, in serve_forever
        contexts = self.generate_contexts(initial_ctx)
      File "/usr/lib64/python2.7/site-packages/spyne/server/_base.py", line 60, in generate_contexts
        ProtocolBase.REQUEST)
      File "/usr/lib64/python2.7/site-packages/spyne/protocol/msgpack.py", line 160, in decompose_incoming_envelope
        assert message == MessagePackRpc.RESPONSE
    AssertionError

`JsonDocument` crashes in client code:

    DEBUG:spyne.interface._base:populating 'spyne_test_server.HelloWorldService ({spyne_test_server}HelloWorldService)' types...
    DEBUG:spyne.interface._base:    adding class "<class 'spyne.model.complex.say_hello'>" for '{spyne.examples.hello}say_hello'
    DEBUG:spyne.interface._base:    adding class "<class 'spyne.model.complex.say_helloResponse'>" for '{spyne.examples.hello}say_helloResponse'
    DEBUG:spyne.interface._base:populating 'spyne_test_server.HelloWorldService' methods...
    DEBUG:spyne.interface._base:    adding method 'say_hello' to match '{spyne.examples.hello}say_hello' tag.
    DEBUG:spyne.interface._base:From this point on, you're not supposed to make any changes to the class & method structure of the exposed services.
    DEBUG:spyne.util.appreg:Registering <spyne.application.Application object at 0x7f3f23bf4810> as ('spyne.examples.hello', 'Application')
    DEBUG:spyne.protocol.dictdoc:   header : None
    DEBUG:spyne.protocol.dictdoc:   body   : {u'faultcode': u'Client', u'faultstring': u'Empty request', u'detail': None}
    Traceback (most recent call last):
      File "spyne_test_client.py", line 6, in <module>
        client.service.say_hello()
      File "/usr/lib64/python2.7/site-packages/spyne/client/zeromq.py", line 43, in __call__
        self.get_in_object(self.ctx)
      File "/usr/lib64/python2.7/site-packages/spyne/client/_base.py", line 144, in get_in_object
        message=self.app.in_protocol.RESPONSE)
      File "/usr/lib64/python2.7/site-packages/spyne/protocol/dictdoc.py", line 218, in decompose_incoming_envelope
        raise ValidationError("Need a dictionary with exacltly one key "
    spyne.error.ValidationError: Fault(Client.ValidationError: 'The value "\'Need a dictionary with exacltly one key as method name.\'" could not be validated.')

`XmlDocument` works as expected. The server prints `hello`.

**Comment by plq** [comment] 2015-08-28 10:45
The clients are a bit neglected because there's no way to parse a WSDL and generate ServiceBase children from it.

Most of the tracebacks here say that the input document is not of expected format. One says (`assert message == MessagePackRpc.RESPONSE`) "This is an output-only protocol"

This has got nothing to do with `@rpc` and friends. Someone should hack the `serialize` methods of the protocols you tried to create the kind of document that `decompose_incoming_envelope` expects.

**Comment by plq** [comment] 2015-09-07 16:12
duplicate of #359

**Closed by plq** 2015-09-07 16:12 UTC
Labels: Defect, Enhancement
